"""
Cookie 池管理模块
==================
功能：
1. 多组 Netscape 格式 Cookie 文件管理
2. 自动加载、轮换、过期检测
3. 支持导入 Chrome/Edge 导出的 Cookie
4. 每 24 小时触发 Cookie 刷新检查
"""

import os
import re
import time
import logging
import shutil
from typing import Optional
from pathlib import Path

logger = logging.getLogger("cookie_pool")

# ─── 常量 ───
COOKIE_DIR = Path(__file__).parent / "cookies"
POOL_FILE = COOKIE_DIR / "cookies_pool.txt"
EXPIRE_CHECK_INTERVAL = 86400  # 24 小时

# 内置抖音访客 Cookie 模板（仅含必要字段）
# 实际使用时建议导入浏览器导出的完整 Cookie
BUILTIN_COOKIES = """# Netscape HTTP Cookie File
# Generated by Cookie Pool Manager
# Domain	Include Subdomains	Path	Secure	Expires	Key	Value
.douyin.com	TRUE	/	FALSE	1893456000	csrf_token	default_csrf
.douyin.com	TRUE	/	FALSE	1893456000	sessionid	default_session
.douyin.com	TRUE	/	FALSE	1893456000	odin_tt	default_odin
.douyin.com	TRUE	/	FALSE	1893456000	passport_fe_beating_status	default_passport
.douyin.com	TRUE	/	FALSE	1893456000	store_region	cn
.douyin.com	TRUE	/	FALSE	1893456000	store_idc	default
.iesdouyin.com	TRUE	/	FALSE	1893456000	csrf_token	default_csrf
.iesdouyin.com	TRUE	/	FALSE	1893456000	sessionid	default_session
"""


class CookiePool:
    """
    Cookie 池
    管理多组 Cookie，支持自动轮换和过期检测。
    """

    def __init__(self, pool_file: str = None):
        self.pool_file = Path(pool_file) if pool_file else POOL_FILE
        self.cookie_groups: list[list[str]] = []   # 每组 Cookie 为多行字符串列表
        self.current_index = 0
        self.last_check_time = 0
        self.failed_groups: set[int] = set()        # 标记失效的组索引
        self._ensure_pool()
        self._load_pool()

    def _ensure_pool(self):
        """确保 Cookie 目录和池文件存在"""
        COOKIE_DIR.mkdir(exist_ok=True)
        if not self.pool_file.exists():
            logger.info(f"Cookie pool not found, creating default: {self.pool_file}")
            with open(str(self.pool_file), "w", encoding="utf-8") as f:
                f.write(BUILTIN_COOKIES)
            logger.warning("Default cookies are placeholders! Import real cookies for production.")

    def _load_pool(self):
        """加载 Cookie 池文件，按空行分隔多组 Cookie"""
        self.cookie_groups = []
        try:
            with open(str(self.pool_file), "r", encoding="utf-8") as f:
                content = f.read()

            # 按空行分隔每组 Cookie
            raw_groups = re.split(r"\n\s*\n", content.strip())

            for group in raw_groups:
                lines = group.strip().split("\n")
                # 过滤注释行和空行
                valid_lines = [
                    line.strip()
                    for line in lines
                    if line.strip() and not line.strip().startswith("#")
                ]
                if valid_lines:
                    self.cookie_groups.append(valid_lines)

            logger.info(f"Loaded {len(self.cookie_groups)} cookie groups from pool")

            if not self.cookie_groups:
                logger.warning("Cookie pool is empty! Using built-in defaults.")
                self.cookie_groups.append(
                    [l for l in BUILTIN_COOKIES.split("\n") if l.strip() and not l.strip().startswith("#")]
                )

        except Exception as e:
            logger.error(f"Failed to load cookie pool: {e}")
            self.cookie_groups = [
                [l for l in BUILTIN_COOKIES.split("\n") if l.strip() and not l.strip().startswith("#")]
            ]

    def get_current_cookie_file(self) -> str:
        """
        获取当前 Cookie 组并写入临时文件
        返回文件路径，供 yt-dlp 使用
        """
        if not self.cookie_groups:
            self._load_pool()

        # 如果当前组已失效，自动切换到下一组
        while self.current_index in self.failed_groups:
            self.current_index = (self.current_index + 1) % max(len(self.cookie_groups), 1)

        group = self.cookie_groups[self.current_index % max(len(self.cookie_groups), 1)]
        cookie_path = str(COOKIE_DIR / "current_cookies.txt")

        with open(cookie_path, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            for line in group:
                f.write(line + "\n")

        return cookie_path

    def rotate(self) -> str:
        """
        切换到下一组 Cookie
        返回新的 Cookie 文件路径
        """
        old_index = self.current_index
        self.current_index = (self.current_index + 1) % max(len(self.cookie_groups), 1)

        # 如果所有组都已尝试过，重置失败标记
        if self.current_index == 0 and len(self.failed_groups) == len(self.cookie_groups):
            logger.warning("All cookie groups exhausted, resetting failure markers")
            self.failed_groups.clear()

        logger.info(f"Rotated cookie: group {old_index} -> {self.current_index}")
        return self.get_current_cookie_file()

    def mark_failed(self, group_index: int = None):
        """标记某组 Cookie 为失效"""
        idx = group_index if group_index is not None else self.current_index
        if idx < len(self.cookie_groups):
            self.failed_groups.add(idx)
            logger.warning(f"Cookie group {idx} marked as failed")
            # 立即尝试切换
            self.rotate()

    def add_cookies(self, cookies_text: str) -> bool:
        """
        导入一组新 Cookie（来自手动导出）
        返回值：是否成功添加
        """
        lines = [l.strip() for l in cookies_text.split("\n") if l.strip() and not l.strip().startswith("#")]
        # 基本格式校验
        valid = 0
        for line in lines:
            parts = line.split("\t")
            if len(parts) >= 7:
                valid += 1

        if valid < 3:
            logger.warning(f"Too few valid cookies ({valid}), rejecting import")
            return False

        self.cookie_groups.append(lines)
        logger.info(f"Imported {valid} cookies as group {len(self.cookie_groups) - 1}")

        # 追加到池文件
        with open(str(self.pool_file), "a", encoding="utf-8") as f:
            f.write("\n# --- Imported Group ---\n")
            for line in lines:
                f.write(line + "\n")

        return True

    def get_pool_stats(self) -> dict:
        """获取 Cookie 池状态统计"""
        expired = 0
        now = time.time()
        for i, group in enumerate(self.cookie_groups):
            for line in group:
                parts = line.split("\t")
                if len(parts) >= 5:
                    try:
                        expires = int(parts[4])
                        if expires < now:
                            expired += 1
                            break
                    except ValueError:
                        pass

        return {
            "total_groups": len(self.cookie_groups),
            "failed_groups": len(self.failed_groups),
            "current_index": self.current_index,
            "has_expired": expired > 0,
            "expired_count": expired,
        }

    def check_expiry(self, force: bool = False):
        """
        检查 Cookie 过期状态
        自动触发条件：距离上次检查超过 24 小时
        """
        now = time.time()
        if not force and (now - self.last_check_time) < EXPIRE_CHECK_INTERVAL:
            return

        self.last_check_time = now
        stats = self.get_pool_stats()
        if stats["has_expired"]:
            logger.warning(f"Found {stats['expired_count']} expired cookies in pool")
            # 标记包含过期 Cookie 的组
            for i, group in enumerate(self.cookie_groups):
                for line in group:
                    parts = line.split("\t")
                    if len(parts) >= 5:
                        try:
                            expires = int(parts[4])
                            if 0 < expires < now:  # 非永久 Cookie 且已过期
                                self.failed_groups.add(i)
                                logger.info(f"Group {i} marked expired")
                                break
                        except ValueError:
                            pass


# 全局单例
cookie_pool = CookiePool()
