"""
Cookie 池生成器
===============
用法:
  python generate_cookies.py                    # 生成默认占位 Cookie
  python generate_cookies.py --import cookies.txt  # 导入浏览器导出的 Cookie

浏览器导出 Cookie 方法:
  1. Chrome: 安装 EditThisCookie 扩展 → 导出 → 选择 Netscape 格式
  2. Edge: 安装 Cookie-Editor 扩展 → 导出 → 选择 Netscape 格式
  3. Firefox: 安装 Cookies.txt 扩展 → 导出
"""

import os
import sys
import argparse
from pathlib import Path

BASE_DIR = Path(__file__).parent
COOKIE_DIR = BASE_DIR / "processors" / "cookies"
POOL_FILE = COOKIE_DIR / "cookies_pool.txt"

DEFAULT_COOKIES = """# Netscape HTTP Cookie File
# Generated by Cookie Pool Generator
# 请用浏览器导出的真实 Cookie 替换以下内容
#
# 导出方法:
#   Chrome: EditThisCookie 扩展 → 导出 Netscape 格式
#   Edge: Cookie-Editor 扩展 → 导出 Netscape 格式
#
# 域名格式: .douyin.com (前面带点表示匹配所有子域名)
#
# Domain	IncludeSubdomains	Path	Secure	Expires	Key	Value
.iesdouyin.com	TRUE	/	FALSE	1893456000	csrf_token	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.iesdouyin.com	TRUE	/	FALSE	1893456000	sessionid	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.iesdouyin.com	TRUE	/	FALSE	1893456000	odin_tt	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.douyin.com	TRUE	/	FALSE	1893456000	csrf_token	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.douyin.com	TRUE	/	FALSE	1893456000	sessionid	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.douyin.com	TRUE	/	FALSE	1893456000	odin_tt	PLACEHOLDER_REPLACE_WITH_REAL_COOKIE
.douyin.com	TRUE	/	FALSE	1893456000	passport_fe_beating_status	1
.douyin.com	TRUE	/	FALSE	1893456000	store_region	cn
.douyin.com	TRUE	/	FALSE	1893456000	store_idc	none
# --- 第二组 Cookie（备用） ---
# Domain	IncludeSubdomains	Path	Secure	Expires	Key	Value
.iesdouyin.com	TRUE	/	FALSE	1893456000	csrf_token	PLACEHOLDER_GROUP2
.iesdouyin.com	TRUE	/	FALSE	1893456000	sessionid	PLACEHOLDER_GROUP2
.iesdouyin.com	TRUE	/	FALSE	1893456000	odin_tt	PLACEHOLDER_GROUP2
"""


def generate_default():
    """生成默认 Cookie 池文件"""
    COOKIE_DIR.mkdir(parents=True, exist_ok=True)
    with open(str(POOL_FILE), "w", encoding="utf-8") as f:
        f.write(DEFAULT_COOKIES)
    print(f"[OK] Default cookie pool created: {POOL_FILE}")
    print("[!] WARNING: Placeholder cookies will NOT work for real parsing!")
    print("[!] Please import real cookies using --import option")


def import_cookies(filepath: str):
    """导入浏览器导出的 Cookie 文件"""
    filepath = Path(filepath)
    if not filepath.exists():
        print(f"[ERROR] File not found: {filepath}")
        return False

    with open(str(filepath), "r", encoding="utf-8") as f:
        raw = f.read()

    # 校验格式
    lines = [l.strip() for l in raw.split("\n") if l.strip() and not l.strip().startswith("#")]
    valid = sum(1 for l in lines if len(l.split("\t")) >= 7)

    if valid < 3:
        print(f"[ERROR] Invalid cookie format: only {valid} valid lines (need >= 3)")
        return False

    # 追加到池文件
    COOKIE_DIR.mkdir(parents=True, exist_ok=True)
    with open(str(POOL_FILE), "a", encoding="utf-8") as f:
        f.write(f"\n# --- Imported from {filepath.name} ---\n")
        for line in lines:
            f.write(line + "\n")

    print(f"[OK] Imported {valid} cookies from {filepath.name}")
    print(f"[OK] Pool file: {POOL_FILE}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Cookie Pool Generator")
    parser.add_argument("--import", dest="import_file", type=str, help="Import cookie file (Netscape format)")
    args = parser.parse_args()

    if args.import_file:
        import_cookies(args.import_file)
    else:
        generate_default()


if __name__ == "__main__":
    main()
